//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhostReplays.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GhostReplays.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!--[if IE 6]&gt;
        ///&lt;html id=&quot;ie6&quot; dir=&quot;ltr&quot; lang=&quot;en-US&quot;&gt;
        ///&lt;![endif]--&gt;
        ///&lt;!--[if IE 7]&gt;
        ///&lt;html id=&quot;ie7&quot; dir=&quot;ltr&quot; lang=&quot;en-US&quot;&gt;
        ///&lt;![endif]--&gt;
        ///&lt;!--[if IE 8]&gt;
        ///&lt;html id=&quot;ie8&quot; dir=&quot;ltr&quot; lang=&quot;en-US&quot;&gt;
        ///&lt;![endif]--&gt;
        ///&lt;!--[if !(IE 6) | !(IE 7) | !(IE 8)  ]&gt;&lt;!--&gt;
        ///&lt;html dir=&quot;ltr&quot; lang=&quot;en-US&quot;&gt;
        ///    &lt;!--&lt;![endif]--&gt;
        ///    &lt;head&gt;
        ///        
        ///        &lt;meta charset=&quot;UTF-8&quot; /&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///        
        ///        &lt;title&gt;Ghostblade Replays&lt;/title&gt;
        ///        
        ///&lt;scr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
    }
}
